// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVTfv2rjPOgyL8Q-rOcNxIx8guhq2o79I',
    appId: '1:40567448444:web:3a46a23a542cd85292faf9',
    messagingSenderId: '40567448444',
    projectId: 'bookeasyapp-6b672',
    authDomain: 'bookeasyapp-6b672.firebaseapp.com',
    storageBucket: 'bookeasyapp-6b672.appspot.com',
    measurementId: 'G-HJS324VCKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3L5r9HOXRO-cns9M1dibEYEbWw548hmA',
    appId: '1:40567448444:android:49cea8ea8cf2571f92faf9',
    messagingSenderId: '40567448444',
    projectId: 'bookeasyapp-6b672',
    storageBucket: 'bookeasyapp-6b672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp7eEdzOJNFi3oIbV8EuwRlp_vw7PTteU',
    appId: '1:40567448444:ios:2174d96d440e77e192faf9',
    messagingSenderId: '40567448444',
    projectId: 'bookeasyapp-6b672',
    storageBucket: 'bookeasyapp-6b672.appspot.com',
    iosBundleId: 'com.example.bookEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp7eEdzOJNFi3oIbV8EuwRlp_vw7PTteU',
    appId: '1:40567448444:ios:2174d96d440e77e192faf9',
    messagingSenderId: '40567448444',
    projectId: 'bookeasyapp-6b672',
    storageBucket: 'bookeasyapp-6b672.appspot.com',
    iosBundleId: 'com.example.bookEasy',
  );

}